version: "3"
volumes:
  php-fpm-socket:
  db-store:
services:
  app:
    container_name: app
    build:
      context: ./dockerfiles/php
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
      - type: bind
        source: ./src
        target: /work/src
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME:-laravel_local}
      - DB_USERNAME=${DB_USER:-phper}
      - DB_PASSWORD=${DB_PASS:-secret}
    depends_on:
      - db
  web:
    container_name: web
    build:
      context: ./dockerfiles/nginx
      dockerfile: Dockerfile
    ports:
      - target: 80
        published: ${WEB_PORT:-80}
        protocol: tcp
        mode: host
      - target: 5173
        published: ${NODE_PORT:-5173}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
      - type: bind
        source: ./src
        target: /work/src
    depends_on:
      - app
  db:
    container_name: mysql
    build:
      context: ./dockerfiles/mysql
      dockerfile: Dockerfile
    ports:
      - target: 3306
        published: ${DB_PORT:-3306}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    environment:
      - MYSQL_DATABASE=${DB_NAME:-laravel_local}
      - MYSQL_USER=${DB_USER:-phper}
      - MYSQL_PASSWORD=${DB_PASS:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-secret}